{% set version = "3.2.1" %}

package:
  name: libarchive
  version: {{ version }}

source:
  fn: libarchive-{{ version }}.tar.gz
  url: https://github.com/libarchive/libarchive/archive/v{{ version }}.tar.gz
  sha256: bcefe75f3f1527656c82e42e7adf1614ae274d005b2583d0ae15f857bfb1ed28

build:
  number: 2
  skip: true  # [win and py36]
  features:
    - vc9  # [win and py27]
    - vc14  # [win and py>=35]

requirements:
  build:
    - toolchain
    - autoconf  # [unix]
    - automake  # [unix]
    - libtool  # [unix]
    - pkg-config  # [unix]
    - bzip2 1.0.*
    - expat
    - libiconv
    - openssl 1.0.*
    - xz 5.2.*
    - zlib 1.2.*

  run:
    - bzip2 1.0.*
    - expat
    - libiconv
    - openssl 1.0.*
    - xz 5.2.*
    - zlib 1.2.*

test:
  commands:
    # Verify pkg-config file is in place.
    - test -f "${PREFIX}/lib/pkgconfig/libarchive.pc"  # [unix]

    # Verify headers are in place.
    - test -f "${PREFIX}/include/archive.h"            # [unix]
    - test -f "${PREFIX}/include/archive_entry.h"      # [unix]
    - if not exist %LIBRARY_PREFIX%\\include\\archive.h exit 1  # [win]

    # Verify libraries are in place.
    - test -f "${PREFIX}/lib/libarchive.a"             # [unix]
    - test -f "${PREFIX}/lib/libarchive${SHLIB_EXT}"   # [unix]
    - if not exist %LIBRARY_PREFIX%\\lib\\libarchive.lib exit 1  # [win]

    # Check for commands
    - bsdcat --version
    - bsdcpio --version
    - bsdtar --version

about:
  home: http://www.libarchive.org/
  summary: Multi-format archive and compression library
  license: BSD 2-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - jakirkham
    - mingwandroid
