{% set version = "3.3.2" %}

package:
  name: libarchive
  version: {{ version }}

source:
  fn: libarchive-{{ version }}.tar.gz
  url: https://github.com/libarchive/libarchive/archive/v{{ version }}.tar.gz
  sha256: 22560b89d420b11a4a724877bc6672b7d7c0f239e77d42a39dcc5a9c3b28db82

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - autoconf  # [unix]
    - automake  # [unix]
    - libtool  # [unix]
    - pkg-config  # [unix]
    - {{ compiler('c') }}
  host:
    - bzip2
    - expat
    - libiconv
    - openssl
    - xz
    - zlib

  run:
    - bzip2
    - expat
    - libiconv
    - openssl
    - xz
    - zlib

test:
  commands:
    # Verify pkg-config file is in place.
    - test -f "${PREFIX}/lib/pkgconfig/libarchive.pc"  # [unix]

    # Verify headers are in place.
    - test -f "${PREFIX}/include/archive.h"            # [unix]
    - test -f "${PREFIX}/include/archive_entry.h"      # [unix]

    # Verify libraries are in place.
    - test -f "${PREFIX}/lib/libarchive.a"             # [unix]
    - test -f "${PREFIX}/lib/libarchive${SHLIB_EXT}"   # [unix]

    # Check for commands
    - bsdcat --version
    - bsdcpio --version
    - bsdtar --version

about:
  home: http://www.libarchive.org/
  summary: Multi-format archive and compression library
  license: BSD 2-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - jakirkham
    - mingwandroid
